### ISSUE TITLE
Torrent ID included despite `DataDirIncludesTorrentID: false`

### ISSUE THREAD

**Issue by weberc2** [cenkalti/rain#154]
When I start a test download, it puts it in `$DATA/tNxjFTcZEe-JaKqnI4_C9g/Big Buck Bunny` when I expect it to be placed in `$DATA/Big Buck Bunny`.

Version v1.12.15

My config is:

```yaml
# /rain/config.yaml
database: /rain/session.db
dataDir: /rain/data
dataDirIncludesTorrentID: false
```

I'm running it with `rain server --config /rain/config.yaml`, and the server seems to be reading the correct file based on the log line:

```
2024-06-30 19:57:46 INFO [rain] main.go:649 config loaded from: /rain/config.yaml
```

Any suggestions about what might be going wrong?
