### ISSUE TITLE
DHT/PEX not working?

### ISSUE THREAD

**Issue by weberc2** [cenkalti/rain#168]
Apologies if I'm misunderstanding what DHT/PEX are for, but my impression is that in cases where magnet links don't include a list of trackers, or the trackers don't have peers for the content, that DHT/PEX should kick in and help rain find trackers with peers, but even after several hours the metadata download doesn't make any progress and `rain client trackers` returns an empty list. Based on the default values in config.go, my understanding is that these features are enabled in rain by default (although I'm behind a firewall, so maybe that's a problem?), but my configuration is as follows:

```yaml
database: /tmp/rain/session.db
datadir: /tmp/rain/data
rpchost: 0.0.0.0
rpcport: 7246 # this seems to be the same as the default for `dhtport`--are these conflicting?
```

Thanks in advance for any help, and please let me know if I can provide any other information to aid in debugging.
